### ISSUE TITLE
Question about the frequency of NDP device.

### ISSUE THREAD

**Issue by QuqqU** [hpc-ulisboa/NDPmulator#2]
Hello!

I really appreciate your opensourced work, particularly the gem5-ndp paper.
It has left a lasting impression on me.

I find myself inquisitive regarding the NDP frequency setup. Specifically, I am wondering if it should be as same as the CPU frequency.
Could you provide guidance on how to set the NDP frequency independently? Or should it ideally match the CPU frequency?

Moreover, I delved into the `/tests/test-progs/ndp` examples and found them quite insightful. However, considering my relatively novice skills with gem5, I'm seeking your expert advice on the preferred method for loading a NDP driver in a full system simulation. I want to ensure a smooth integration, and any recommendations you have would be immensely helpful.

Thank you for your time and for sharing your invaluable insights!

**Comment by joaomiguelvieira** [comment]
Hi!

When scheduling events in gem5, the specified clock cycles refer to the simulator's global clock (typically much higher than the CPU's). When you start gem5, it should output the following line: ``Global frequency set at 1000000000000 ticks per second``. This indicates that the global frequency used by the simulator is 1 THz per second. Therefore, if you want your NDP accelerator to work at a given frequency (let's say 1 GHz), you should consider that every NDP cycle elapsed corresponds to 1000 cycles in gem5.

Regarding the driver, the example at ``tests/test-progs/ndp/device_driver`` illustrates a standard Linux device driver for the given NDP accelerator. To use it, you will have to compile it (by typing ``make``) and transfer it to the virtual disk image (you can mount the virtual disk into your host system, transfer the files, and then use it in gem5). Then, start gem5 FS mode. To load the driver in FS mode, just type ``make load``.

I hope this answers your questions. 

If you still have any doubts, let me know!

**Comment by QuqqU** [comment]
I really appreciate your kind answer :)
